name = "makers-doctor-guy"
main = "src/index.ts"
compatibility_date = "2023-01-11"

kv_namespaces = [
    { binding = "MAKERS_DOCTOR_GUY", id = "4648a3a5ca8740f696ddcd5ccd7b86d8", preview_id = "f6ad865027184bf8bfcdafd81dfd3bfb" }
]

[triggers]
crons = [ "*/1 * * * *" ]


# The necessary secrets are:
# - SLACK_BOT_API_TOKEN
# Run `echo <VALUE> | wrangler secret put <NAME>` for each of these